### ISSUE TITLE
Clean up AddThisElement & AddThisWrapper pre-render/twig templates. 

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/addthis#16]
- Remove the RenderElement code and twig templates for AddThisElement and AddThisWrapper. 
- Update the AddThisBlock class to setup the data to pass to rendering. Most of the logic can be handled in a twig template rather than in the build() function.
- Update the AddThisBasicToolbox and AddThisBasicButton Render Elements to setup the variables to pass to Twig templates.
- Update the twig templates to handle the logic that the build() function used to do. 
- Refine documentation in PreRender/Twig templates per implementation

Driving Factors: All display logic should be handled in the theme layer.

**Comment by doylejd** [comment]
@ChuChuNaKu Lets chat about this with @jenter  later today. @damontgomery gave us some good feedback last week and we can get this ticket fleshed out better for you to work on.

**Comment by ChuChuNaKu** [comment]
@doylejd ok, sounds good.

**Comment by doylejd** [comment]
Great work on this Jaleel. Closing this issue since #40 got merged.
