### ISSUE TITLE
Fix Admin Settings Page

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/addthis#4]
There are several form/styling issues on the AddThis Admin page. (admin/config/user-interface/addthis)

@TODO:
- Fieldsets should be collapsable.
- ~~Enabled Services & Compact Menu Enabled Services labels are overlapping~~

**Comment by nerdstein** [comment]
@pninny2001 wanna tackle this one?

**Comment by msherron** [comment]
Done and merged. Closing.
