### ISSUE TITLE
Advanced AddThis Settings Form cant be accessed through UI

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/addthis#5]
The Advanced AddThis Settings page is not accessible through the configuration menu. 
- URL can be accessed here /admin/config/user-interface/addthis/advanced

@TODO:
- Fix the menu routing to allow users to access the advanced AddThis settings. Would be ideal if this was a tabbed interface for Basic/Advanced settings.

**Comment by msherron** [comment]
Created PR https://github.com/d8-contrib-modules/addthis/pull/14.

**Comment by nerdstein** [comment]
Merged, closing
