### ISSUE TITLE
Add "Administer AddThis Settings" permission

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/addthis#6]
Permissions for menu paths are currently set to "administer site configuration". This should be updated to a custom addthis permission. 

@TODO:
- Add new permission "administer addthis settings" and apply to routing.
- Add new permission "administer advanced addthis settings" and apply to routing.

**Comment by msherron** [comment]
Created PR https://github.com/d8-contrib-modules/addthis/pull/13

**Comment by nerdstein** [comment]
PR merged
