### ISSUE TITLE
Abstract out addthis_fields and addthis_block submodule

### ISSUE THREAD

**Issue by doylejd** [d8-contrib-modules/addthis#8]
Abstract out the Field Formatters for AddThisBasicButtonFormatter.php and AddThisBasicToolboxFormatter.php into the addthis_displays module. 

We want to keep the basic module setup as:
- addthis - The basic API integration to interface with AddThis. Provides no rendering for AddThis elements.
- addthis_fields - Provides field formatters to allow rendering AddThis in content types.
- addthis_block - Provides configurable AddThis block plugin to be used.

**Comment by doylejd** [comment]
PR for this is up here: https://github.com/d8-contrib-modules/addthis/pull/12

**Comment by nerdstein** [comment]
Merged, closing
